version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    command: npm start
    ports:
      - "8000:3000"
    volumes:
      - /usr/src/node_modules
      - .:/usr/src